# This file is auto-generated by GitHub Actions.
# Do not edit by hand — it will be overwritten on the next build.
class Jcc < Formula
  desc "jcc (Jira Cloud Copilot) — terminal UI for Jira workflows: standup, tickets, dates, and activity"
  homepage "https://github.com/ARPA-H/jira-copilot"
  version "0.0.115"
  license "MIT"

  on_arm do
    url "https://github.com/ARPA-H/homebrew-tap/releases/download/jcc%2F0.0.115/jcc-0.0.115-aarch64-apple-darwin.tar.gz"
    sha256 "f6809bfef0c905bf4c8f6049fb173c6cefeb82d6312c6ab9df7a82fcd62a3193"
  end

  def install
    bin.install "jcc"
  end

  test do
    assert_predicate bin/"jcc", :executable?
  end
end
