# This file is auto-generated by GitHub Actions.
# Do not edit by hand — it will be overwritten on the next build.
class Jcc < Formula
  desc "jcc (Jira Cloud Copilot) — terminal UI for Jira workflows: standup, tickets, dates, and activity"
  homepage "https://github.com/ARPA-H/jira-copilot"
  version "0.0.123"
  license "MIT"

  on_arm do
    url "https://github.com/ARPA-H/homebrew-tap/releases/download/jcc%2F0.0.123/jcc-0.0.123-aarch64-apple-darwin.tar.gz"
    sha256 "9759059cada98a4381b5f2165e58681a56b2b9a986266f56e34895865f7f7cff"
  end

  def install
    bin.install "jcc"
  end

  test do
    assert_predicate bin/"jcc", :executable?
  end
end
